server:
    port: 8081
spring:
    application:
        name: USER-SERVICE
    config:
        import: optional:configserver:http://localhost:8085
    datasource:
        url: jdbc:mysql://localhost:3306/microservices?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
management:
    health:
        circuitbreakers:
            enabled: true
        enpoints:
            web:
                exposure:
                    inlude: health
        enpoint:
            health:
                show-details: always

resilience4j:
  circuitbreaker:
      instances:
          ratingHotelBreaker:
              registerHealthIndicator: true
              eventConsumerBufferSize: 10
              failureRateThreshold: 50
              slidingWindowSize: 10
              minimumNumberOfCalls: 5
              automatic-transition-from-open-to-half-open-enabled: true
              wait-duration-in-open-state: 6s
              permitted-number-of-calls-in-half-open-state: 3
              sliding-window-type: count_based
      retry:
          instances:
              ratingHotelService:
                  max-attempts: 3
                  wait-duration: 5s






